---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "micro-two.fullname" . }}
  {{ if .Values.ambassador.enabled -}}
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  Mapping
      name:  {{ .Values.service.name }}_mapping
      prefix: /{{ .Values.service.name }}/
      service: {{ template "micro-two.fullname" . }}.default.svc.cluster.local:8088
      host_rewrite: {{ template "micro-two.fullname" . }}.default.svc.cluster.local
  {{- end }}
  labels:
    app: {{ template "micro-two.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    generator: micro-kube
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app: {{ template "micro-two.name" . }}
    release: {{ .Release.Name }}
